Merge dev into master for code review
hadar759/enchanted-swiftie pull request #2
Opened 2019-08-09 14:44 UTC by hadar759

2019-08-09 17:51 UTC, tomgrin10 requested changes

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +        self.answers = ["Taylor thinks it is certain",
Put this into a global variable or as a resource in a file

2019-08-09 17:51 UTC, tomgrin10 commented on .gitignore
> +# pycharm
PyCharm not pycharm

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +    def __init__(self, bot):
add type hints

2019-08-09 17:51 UTC, tomgrin10 commented on .gitignore
> +.idea/
add all .pyc files to gitignore.
you want to commit only code, not compiled files.

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +with open(r"support files\google shit.txt", "rt") as codes:
- remove spaces from your file names
- `google shit.txt` is not a descriptive name
- `support files` is not a good name either, look at existing conventions for such folders, maybe call it `data` or `resources` idk

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +with open(r"support files\google shit.txt", "rt") as codes:
`codes` is not a good variable name for a file object, maybe `gis_codes_file`?

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +# Stores the feature current status - True for on False for off
???

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +import random
read https://www.python.org/dev/peps/pep-0008/#imports
then press Alt+Ctrl+O in pycharm in this file

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +    async def tay_ball(self, ctx, *, question):
add type hints

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +    async def event(self, ctx, *, event_name=""):
add type hints

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +    def answer_selector(self, question) -> int:
add type hints

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +    def query_creator(self, event_name) -> str:
add type hints

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +with open(r"support files\google shit.txt", "rt") as codes:
I think you mistakenly didn't commit `google shit.txt`

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +    async def tay_ball(self, ctx, *, question):
change the name of the function to `command_tay_ball` to signify this is in fact a command function, and not a regular function, and add `name="tay_ball"` to previous line.
Do this to all commands.

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +        except Exception as e:
Catch a more specific exception.

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +            if str(e).find("400 BAD REQUEST") != -1 or str(e).find("HttpError") != -1:
Don't base your behavior on the `str()` of the exception, base it on the type of the exception using multiple excepts.

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +                await ctx.send("User image quota filled, please wait a minute and try again")
Nice that you thought about all this stuff and you are handling it!

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +            # Daily quota filled, google won't provide more urls
Great comments overall in this function!!

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +    async def tay_ball(self, ctx, *, question):
if the name of the command is `tayball` maybe name the function `tayball` instead of `tay_ball`? just something to think about, not necessary.

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +        """Sends Taylorized 8ball self.answers"""
you mistakenly renamed a word in this line 😘

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +    def answer_selector(self, question) -> int:
function name is not good, function names should describe an action or a question, maybe `select_tayball_answer` or `answer_tayball_question`.

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +        if question.find("new romantics") != -1 or question.find("wildest dreams") != -1:
str.find is for finding the index of a substring, if you want to check for the existence of a substring use the `in` keyword
```suggestion
        if "new romantics" in question or "wildest dreams" in question:
```
you can even do this:
```suggestion
        if any(substr in question for substr in ["new romantics", "wildest dreams"]):
```

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +    def query_creator(self, event_name) -> str:
bad function name

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +            if question.find("best") != -1 or question.find("good") != -1 \
after reading last comment, you can change this to:
```suggestion
            if any(substr in question for substr in GOOD_ADJECTIVES):
```
where `GOOD_ADJECTIVES` is a list of all the good words.

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +    def query_creator(self, event_name) -> str:
This method can be a static method

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +            query = "Taylor Swift " + random.choice("123456789") + random.choice("123456789") + \
https://docs.python.org/3/library/random.html#random.randrange

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +import billboard
read https://www.python.org/dev/peps/pep-0008/#imports
then press Alt+Ctrl+O in pycharm in this file

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +import datetime as dt
don't make aliases

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/support files/billboard.txt
> +cGraw - 40
stUPID

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/main.py
> +from discord.ext import commands
Ctrl+Alt+O

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/main.py
> +def main():
Great main file!!!

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +    async def singles(self, ctx):
add type hints

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +    def add_singles_to_dict(self, chart):
add type hints

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +    def read_singles_info(self):
add type hints

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +    def format_message(self) -> str:
nice type hints!!

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +    def __init__(self, bot):
add type hints

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +        self.last_checked = None
add type hint
```suggestion
         from typing import Optional

        self.last_checked: Optional[dt.datetime] = None
```

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +        while self.last_checked + dt.timedelta(7) < dt.datetime.date(dt.datetime.now()):
`dt.timedelta(7)` is not clear, 7 what?
when positional arguments are not clear, use keyword arguments: `dt.timedelta(days=7)`
or even clearer: `dt.timedelta(weeks=1)`

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +    def format_message(self) -> str:
function name not descriptive

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +        """Formatting the dict into a message the bot can send"""
format documentation like a TODO item, not in present progressive
```suggestion
        """Format the singles dict into a message the bot can send"""
```

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +        for single in self.singles_dict.items():
use tuple unpacking
```suggestion
        for single_name, single_placement in self.singles_dict.items():
```

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +            message += f"{single[0]} - {single[1]}\n"
```suggestion
            message += f"{single_name} - {single_placement}\n"
```

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +        self.singles_dict = {}
the type checker will understand this is a dict, but we also want to specify the types of the keys and values.
```suggestion
        from typing import Dict

        self.singles_dict: Dict[str, int] = {}
```

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +        with open(r"support files\billboard.txt", "w") as file:
file is an existing name
```suggestion
        with open(r"support files\billboard.txt", "w") as singles_file:
```

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +        for entry_place in range(len(chart)):
if you need the index, use enumerate
```suggestion
        for entry_place, entry in enumerate(chart):
```

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +                elif entry_place < self.singles_dict[entry.title]:
no need for this elif, you can put an `or` in the last if

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +            # Turns the string into a Year, month and day variables by hand
no need to do this by hand, read about `datetime` parsing

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +        with open(r"support files\billboard.txt", "r") as file:
again, `file` is already a name, use `singles_file`

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +            for line in file.readlines():
use dict comprehension to replace this whole loop

2019-08-09 17:51 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +        self.last_checked = None
last what checked? variable name isn't descriptive

2019-08-09 17:53 UTC, hadar759 commented on .gitignore
> +# pycharm
fuck you

2019-08-10 08:51 UTC, hadar759 commented on enchanted-swiftie/cogs/misc_chat.py
> +    async def tay_ball(self, ctx, *, question):
חשבתי להפריד אנערף

2019-08-10 09:40 UTC, hadar759 commented on enchanted-swiftie/cogs/misc_chat.py
> +            if question.find("best") != -1 or question.find("good") != -1 \
אהבתי

2019-08-10 09:45 UTC, hadar759 commented on enchanted-swiftie/cogs/misc_chat.py
> +    def query_creator(self, event_name) -> str:
כן אני לא מבין מה זה זה כבר אמר לי

2019-08-10 18:34 UTC, tomgrin10 requested changes

2019-08-10 18:34 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +        if any(substr in question for substr in GOOD_SONGS):
`substr` is not a good variable name, change to `song`

2019-08-10 18:34 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +            if any(substr in question for substr in GOOD_ADJECTIVES):
`substr` is not a good variable name, change to `adjective`

2019-08-10 18:34 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +        self.answers = []
list of what? add type hints for that, (similar to how you added type hints for dict in the next file)

2019-08-10 18:34 UTC, tomgrin10 commented on enchanted-swiftie/cogs/misc_chat.py
> +            query = "Taylor Swift " + str(random.randrange(1, 10)) + str(random.randrange(1, 10)) + \
hadar are you serious
```suggestion
            query = "Taylor Swift " + random.randrange(1000)
```

2019-08-10 18:34 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +            self.singles_dict = {single.split(" - ")[0]: single.split(" - ")[1] for single in singles_file.readlines()}
you can make a dict out of a list of tuples, you can use that to make this line better
```suggestion
            self.singles_dict = dict(single.split(" - ") for single in singles_file.readlines())
```

2019-08-10 20:06 UTC, tomgrin10 commented on enchanted-swiftie/cogs/songs.py
> +                if entry.title not in self.singles_dict.keys() or entry_place < self.singles_dict[entry.title]:
no need `.keys()`

2019-08-10 20:36 UTC, merged